version: "3.7"

services:
  hotel-postgresql:
    restart: always
    image: postgres:12.2
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    restart: always
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - hotel-postgresql
    volumes:
      - .:/opt/project:delegated
    extra_hosts:
      - "host.docker.internal:host-gateway"
  