# Generated by Django 4.2.2 on 2023-06-10 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Номер")),
                (
                    "room_class",
                    models.CharField(
                        choices=[
                            ("Эконом", "Economy"),
                            ("Стандарт", "Standard"),
                            ("Стандарт улучшенный", "Standard Superior"),
                            ("Полулюкс", "Junior Suite"),
                            ("Люкс", "Luxury"),
                        ],
                        max_length=20,
                        verbose_name="Класс номера",
                    ),
                ),
                ("floor", models.IntegerField(verbose_name="Этаж")),
                (
                    "rooms_number",
                    models.PositiveIntegerField(verbose_name="Количество комнат"),
                ),
                (
                    "bathroom_type",
                    models.CharField(
                        choices=[
                            ("Совмещенный", "Combined"),
                            ("Раздельный", "Separate"),
                        ],
                        max_length=12,
                        verbose_name="Тип санузла",
                    ),
                ),
                ("has_tv", models.BooleanField(verbose_name="Наличие ТВ")),
                ("has_phone", models.BooleanField(verbose_name="Наличие телефона")),
                (
                    "has_air_conditioning",
                    models.BooleanField(verbose_name="Наличие кондиционера"),
                ),
                (
                    "has_refrigerator",
                    models.BooleanField(verbose_name="Наличие холодильника"),
                ),
                ("has_balcony", models.BooleanField(verbose_name="Наличие балкона")),
                (
                    "is_non_smoking",
                    models.BooleanField(verbose_name="Номер для некурящих"),
                ),
                (
                    "additional_amenities",
                    models.TextField(verbose_name="Дополнительные удобства"),
                ),
                (
                    "price_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        verbose_name="Стоимость за сутки",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hotel.hotel",
                        verbose_name="Отель",
                    ),
                ),
            ],
        ),
    ]
