# Generated by Django 4.2.2 on 2023-06-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "Номер", "verbose_name_plural": "Номера"},
        ),
        migrations.AddField(
            model_name="room",
            name="place_count",
            field=models.PositiveIntegerField(default=1, verbose_name="Число мест"),
        ),
        migrations.AlterField(
            model_name="room",
            name="bathroom_type",
            field=models.CharField(
                choices=[("Совмещенный", "Combined"), ("Раздельный", "Separate")],
                default="Совмещенный",
                max_length=12,
                verbose_name="Тип санузла",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_class",
            field=models.CharField(
                choices=[
                    ("Эконом", "Economy"),
                    ("Стандарт", "Standard"),
                    ("Стандарт улучшенный", "Standard Superior"),
                    ("Полулюкс", "Junior Suite"),
                    ("Люкс", "Luxury"),
                ],
                default="Эконом",
                max_length=20,
                verbose_name="Класс номера",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="rooms_number",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Количество комнат"
            ),
        ),
    ]
