# Generated by Django 4.2.2 on 2023-06-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest", "0002_alter_guest_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guest",
            name="hotel",
        ),
        migrations.AddField(
            model_name="guest",
            name="address",
            field=models.TextField(default="", verbose_name="Адрес"),
            preserve_default=False,
        ),
    ]
